### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mariamm99** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-rafacab1#1]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-rafacab1/blob/b10644c7dcae0c0824a7509b0b164ccef51a817b/ej20.java#L40

**Comment by mariamm99** [comment]
Error el nombre de archivo y el nombre de clase es diferente.

**Comment by rafacab1** [comment]
Anda... Es verdad, vaya fallo mas tonto... Gracias por avisar!

**Comment by mariamm99** [comment]
De nada
